# Site settings
title: Sean Ring
email: sean.ring@finlingo.com
url: https://seaniechaos.github.io
description: "Sean Ring, CAIA, FRM is the Co-Founder and CEO of Finlingo Limited, a Hong Kong-based company.  He is a financial and soft skills trainer who specializes in helping bankers covert their detailed knowledge into plain words that will persuade their clients to buy their ideas."
keywords: "Sean Ring, Finlingo, financial trainer, sales trainer, corporate trainer, soft skills trainer, writer, blogger, developer"
skills: "Co-Founder and CEO of Finlingo | Financial Trainer | Writer and Developer"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4A18BC #80B3FF
  primary-rgb: "74,24,188" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sean Ring, CAIA, FRM
  location: Hong Kong
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SeanRing
  - title: linkedin
    url: https://www.linkedin.com/in/seanring/
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/seaniechaos

# Postal address (add as many lines as necessary)
address:
  - line: 903 Dannies House
  - line: 20 Luard Road
  - line: Wan Chai
  - line: Hong Kong SAR

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
